# Exercise 2.c working with multiple DataFrames

In [1]:
import pandas as pd
import numpy as np

## Basic Aggregations

Create a DataFrame named df_sales using the following data:

In [2]:
data = {'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],
'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East',
'West', 'North'],
'Units_Sold': [10, 15, 20, 5, 10, 15, 10, 5, 15],
'Price': [100, 200, 150, 100, 200, 150, 100, 200, 150]}

In [3]:
df_sales = pd.DataFrame(data)

In [4]:
df_sales

  Product Region  Units_Sold  Price
0       A  North          10    100
1       B  South          15    200
2       C   East          20    150
3       A   West           5    100
4       B  North          10    200
5       C  South          15    150
6       A   East          10    100
7       B   West           5    200
8       C  North          15    150

Add a new column Revenue to df_sales by multiplying Units_Sold and Price

In [5]:
df_sales['Revenue'] = df_sales['Units_Sold'] * df_sales['Price']

In [16]:
df_sales

  Product Region  Units_Sold  Price  Revenue
0       A  North          10    100     1000
1       B  South          15    200     3000
2       C   East          20    150     3000
3       A   West           5    100      500
4       B  North          10    200     2000
5       C  South          15    150     2250
6       A   East          10    100     1000
7       B   West           5    200     1000
8       C  North          15    150     2250

Use the sum function to calculate the total Units_Sold and total Revenue across all
products and regions.

In [8]:
total_units_sold = df_sales['Units_Sold'].sum()
total_revenue = df_sales['Revenue'].sum()

In [9]:
print(f'total units sold is {total_units_sold}')

total units sold is 105

In [10]:
print(f'total revenue is {total_revenue}')

total revenue is 16000

Use the mean function to calculate the average Units_Sold and average Revenue.

In [12]:
avg_units = df_sales['Units_Sold'].mean()
avg_revenue = df_sales['Revenue'].mean()

In [13]:
print(avg_units)
print(avg_revenue)

11.666666666666666
1777.7777777777778

# Grouping Data

Use the groupby function to group df_sales by Product and calculate the total
Units_Sold and total Revenue for each product.

In [17]:
products_grouppp = df_sales.groupby('Product')[['Units_Sold','Revenue']].sum()

In [20]:
products_grouppp

         Units_Sold  Revenue
Product
A                25     2500
B                30     6000
C                50     7500

Use the groupby function to group df_sales by Region and calculate the average
Units_Sold and average Revenue for each region.

In [21]:
region_group = df_sales.groupby('Region')[['Units_Sold','Revenue']].mean()

region_group

Use the groupby function to group df_sales by both Product and Region and
calculate the sum of Units_Sold and Revenue for each combination

In [25]:
P_R_group = df_sales.groupby(['Product','Region'])[['Units_Sold','Revenue']].sum()

P_R_group

## Sorting and Ranking Data

 Sort df_sales by Units_Sold in ascending order

In [39]:
sort_units = df_sales.sort_values(by='Units_Sold')
sort_units

  Product Region  Units_Sold  Price  Revenue
3       A   West           5    100      500
7       B   West           5    200     1000
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
1       B  South          15    200     3000
5       C  South          15    150     2250
8       C  North          15    150     2250
2       C   East          20    150     3000

Sort df_sales by Revenue in descending order

In [43]:
rev_sort = df_sales.sort_values(by='Revenue',ascending=False)

In [44]:
rev_sort

  Product Region  Units_Sold  Price  Revenue
1       B  South          15    200     3000
2       C   East          20    150     3000
8       C  North          15    150     2250
5       C  South          15    150     2250
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
7       B   West           5    200     1000
3       A   West           5    100      500

Add a new column Revenue_Rank to df_sales, which ranks the Revenue values in
descending order (i.e., highest revenue has rank 1)

In [47]:
df_sales['Revenue_Rank'] = df_sales['Revenue'].rank(ascending=False)

In [48]:
df_sales

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank
0       A  North          10    100     1000           7.0
1       B  South          15    200     3000           1.5
2       C   East          20    150     3000           1.5
3       A   West           5    100      500           9.0
4       B  North          10    200     2000           5.0
5       C  South          15    150     2250           3.5
6       A   East          10    100     1000           7.0
7       B   West           5    200     1000           7.0
8       C  North          15    150     2250           3.5

## Merging DataFrames

 Create a new DataFrame named df_products with the following data

In [51]:
product_data = {'Product': ['A', 'B', 'C'],
'Category': ['Electronics', 'Furniture', 'Appliances']}
df_products = pd.DataFrame(product_data)

In [53]:
df_products = pd.DataFrame(product_data)

In [54]:
df_products

  Product     Category
0       A  Electronics
1       B    Furniture
2       C   Appliances

Merge df_sales with df_products on the Product column, resulting in a new
DataFrame named df_merged

In [55]:
df_merged = pd.merge(df_sales,df_products,on='Product')

In [56]:
df_merged

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank     Category
0       A  North          10    100     1000           7.0  Electronics
1       B  South          15    200     3000           1.5    Furniture
2       C   East          20    150     3000           1.5   Appliances
3       A   West           5    100      500           9.0  Electronics
4       B  North          10    200     2000           5.0    Furniture
5       C  South          15    150     2250           3.5   Appliances
6       A   East          10    100     1000           7.0  Electronics
7       B   West           5    200     1000           7.0    Furniture
8       C  North          15    150     2250           3.5   Appliances

Use groupby on df_merged to calculate the total Revenue by Category

In [63]:
group_merged_revenue = df_merged.groupby('Category')[['Revenue']].sum()

In [64]:
group_merged_revenue

             Revenue
Category
Appliances      7500
Electronics     2500
Furniture       6000